### ISSUE TITLE
Rounded Icon mask alignment off

### ISSUE THREAD

**Issue by gumho** [jshmllr/iOS10StickerPackSketch#1]
I found that in the Sketch template, the rounded icon masks are not aligned correctly and result in a small gap on the sides.

The following is a zoomed in screenshot of my app's icon in the iMessage apps view. See how the left and right edges of the icon are not fully flush against the side.
<img width="124" alt="screen shot 2017-01-08 at 10 24 21 pm" src="https://cloud.githubusercontent.com/assets/112738/21758535/a007ecca-d5f1-11e6-9dd2-58ca0be0daf1.png">

**Comment by jshmllr** [comment]
Thanks for this @gumho . Are you experiencing any issues with the system icons too (87x87px size)?
The mask is set to 100px rounded corners on a rectangle, so I'll come up with a new solution or it may possibly be 98px rounded corners.

**Comment by gumho** [comment]
`Are you experiencing any issues with the system icons too (87x87px size)?`
So far I haven't but then again I'm not too sure where those icons are supposed to appear. In my testing, I've only ever seen the rounded rectangular ones being used.

**Comment by jshmllr** [comment]
I'm going to abandon this entire repo for now because  released a template here: https://developer.apple.com/design/resources/#ios-apps
